# -*- coding: utf-8 -*-
"""2218030_Visualisasi Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fDJRolWzem1OBrdWqBsblQ5rhuoZNVAx

1. HUBUNGKAN COLAB DENGAN GDRIVE
"""

from google.colab import drive
drive.mount('/content/drive')

"""2. ARAHKAN KE FOLDER DATASET"""

import os
os.listdir('/content/drive/MyDrive/Colab Notebooks')

"""3. IMPORT LIBRARY DASAR"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""4. BACA DATASET"""

data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Nike Dataset.csv')
data.head()

"""5. CEK INFORMASI DATASET"""

data.info()
data.describe()
data.isnull().sum()

"""6. VISUALISASI DASAR

A. HISTOGRAM
"""

data.hist(figsize=(12,8))
plt.show()

"""        B. SCATTER PLOT"""

plt.figure(figsize=(8,6))
sns.scatterplot(x='Price per Unit', y='Total Sales', data=data)
plt.title('📈 Hubungan antara Harga per Unit dan Total Penjualan')
plt.xlabel('Harga per Unit')
plt.ylabel('Total Penjualan')
plt.show()

"""        C. HEATMAP"""

plt.figure(figsize=(8,6))
sns.heatmap(data[['Price per Unit','Total Sales','Units Sold']].corr(), annot=True, cmap='coolwarm', linewidths=0.5)
plt.title('📉 Korelasi Antar Variabel Numerik')
plt.show()

"""        D. BOXPLOT"""

plt.figure(figsize=(8,6))
sns.boxplot(data=data[['Price per Unit', 'Total Sales', 'Units Sold']])
plt.title('📦 Deteksi Outlier pada Kolom Numerik')
plt.show()

"""        E. COUNTPLOT"""

plt.figure(figsize=(7,5))
sns.countplot(x='Sales Method', data=data)
plt.title('🧁 Jumlah Transaksi per Metode Penjualan')
plt.xlabel('Metode Penjualan')
plt.ylabel('Jumlah Transaksi')
plt.show()

"""        F. SCATTER BERDASARKAN WARNA PRODUK"""

plt.figure(figsize=(8,6))
sns.scatterplot(x='Price per Unit', y='Total Sales', hue='Product', data=data)
plt.title('📈 Hubungan Harga vs Penjualan per Produk')
plt.xlabel('Harga per Unit')
plt.ylabel('Total Penjualan')
plt.legend(title='Product', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()