# -*- coding: utf-8 -*-
"""EDA_2218030.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jtm1SfM7UjkZmolxuDTgiQdZhjXNJIug

1. Import Libraries
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

"""2. Load Dataset"""

df = pd.read_csv  ('/content/drive/MyDrive/Colab Notebooks/Nike Dataset.csv')
df.head()

"""Data diambil dari : https://www.kaggle.com/datasets/krishnavamsis/nike-sales

3. Cek Informasi Dataset
"""

# Informasi umum dataset
df.info()

# Statistik deskriptif
df.describe()

# Cek jumlah data null
df.isnull().sum()

# Cek tipe data
df.dtypes

"""4. Cek Duplikasi & Missing Value"""

# Jumlah data duplikat
df.duplicated().sum()

# Visualisasi missing value
plt.figure(figsize=(10,5))
sns.heatmap(df.isnull(), cbar=False, cmap='viridis')
plt.title('Missing Value Heatmap')
plt.show()

"""5. Analisis Univariate (Satu Variabel)"""

# Kolom numerik
num_cols = df.select_dtypes(include=np.number).columns
df[num_cols].hist(figsize=(12,8), bins=20, color='skyblue')
plt.suptitle('Distribusi Kolom Numerik')
plt.show()

# Kolom kategorikal
cat_cols = df.select_dtypes(exclude=np.number).columns
for col in cat_cols:
    plt.figure(figsize=(6,4))
    sns.countplot(data=df, x=col, palette='viridis')
    plt.title(f'Countplot {col}')
    plt.xticks(rotation=45)
    plt.show()

"""6. Analisis Bivariate (Dua Variabel)"""

# Korelasi antar variabel numerik
plt.figure(figsize=(10,6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title('Heatmap Korelasi')
plt.show()

# Scatter plot (contoh)
sns.scatterplot(data=df, x='colom_x', y='colom_y', hue='colom_kategori')
plt.title('Hubungan antar variabel')
plt.show()

# Boxplot buat liat outlier
sns.boxplot(data=df, x='colom_kategori', y='colom_numerik')
plt.title('Boxplot per kategori')
plt.show()

"""7. Analisis Outlier"""

# Gunakan boxplot semua kolom numerik
for col in num_cols:
    plt.figure(figsize=(6,4))
    sns.boxplot(x=df[col], color='lightgreen')
    plt.title(f'Outlier pada {col}')
    plt.show()

"""8. Insight Awal (Hasil Analisis Data Penjualan)

1️⃣ Missing Value Analysis
Berdasarkan heatmap missing value, seluruh kolom seperti Invoice Date, Product, Region, Retailer, Sales Method, State, Price per Unit, Total Sales, dan Units Sold tidak memiliki missing value. Artinya data sudah bersih dan siap digunakan untuk analisis lebih dalam tanpa perlu proses imputasi.

2️⃣ Distribusi Sales Method
Visualisasi Countplot Sales Method menunjukkan bahwa:

Penjualan Online mendominasi dengan jumlah transaksi tertinggi.

Diikuti oleh Outlet di posisi kedua.

Sedangkan In-store memiliki jumlah transaksi paling sedikit.
👉 Hal ini menandakan bahwa kanal penjualan berbasis digital menjadi saluran utama, kemungkinan karena jangkauan dan kemudahan akses pelanggan yang lebih besar.

3️⃣ Distribusi Penjualan per State
Dari Countplot State, terlihat bahwa:

New York dan California menjadi dua negara bagian dengan transaksi terbanyak.

Distribusi antar state cukup bervariasi, menandakan ada potensi pasar yang belum merata di seluruh wilayah.
👉 Ini bisa jadi peluang ekspansi untuk meningkatkan penjualan di state dengan volume rendah.

4️⃣ Korelasi Antar Variabel Numerik
Pada heatmap korelasi, ditemukan bahwa:

Units Sold memiliki korelasi sangat kuat dengan Total Sales (0.91), yang berarti semakin banyak unit terjual, semakin besar total penjualan.

Price per Unit memiliki korelasi sedang dengan Total Sales (0.44), artinya harga per unit tidak sepenuhnya menentukan total penjualan.
👉 Dengan kata lain, peningkatan jumlah penjualan unit lebih berdampak signifikan daripada menaikkan harga.

5️⃣ Hubungan Units Sold dan Total Sales (Scatter Plot)
Grafik scatter menunjukkan tren positif yang jelas: semakin banyak Units Sold, semakin besar Total Sales.

Pola ini konsisten di semua kategori produk, seperti Men’s Street Footwear dan Women’s Apparel.

Ada beberapa titik di luar tren umum (outlier) yang kemungkinan disebabkan oleh penjualan besar pada produk tertentu (promo, musiman, atau high demand).

6️⃣ Distribusi Total Sales per Product (Boxplot)
Boxplot memperlihatkan bahwa:

Produk dengan penjualan tinggi seperti Men’s Street Footwear dan Women’s Apparel memiliki sebaran data yang luas dan banyak outlier positif, menandakan variasi transaksi yang besar.

Sebaliknya, produk seperti Men’s Athletic Footwear punya sebaran penjualan yang lebih sempit dan stabil.

7️⃣ Outlier Analysis
Boxplot Units Sold menunjukkan adanya outlier di sisi kanan (nilai sangat tinggi), yang menandakan ada beberapa transaksi dengan jumlah unit terjual luar biasa besar.
👉 Ini bisa jadi karena pembelian grosir, event diskon besar, atau produk dengan permintaan tinggi.

8️⃣ Kesimpulan Awal
Secara keseluruhan:

Data penjualan bersih dan tidak ada missing value.

Kanal Online menjadi sumber utama pendapatan.

Korelasi kuat antara Units Sold dan Total Sales menegaskan bahwa peningkatan volume penjualan berpengaruh langsung pada pendapatan.

Produk tertentu seperti Footwear dan Apparel menjadi kontributor besar terhadap total penjualan.

Beberapa outlier berpotensi menjadi titik fokus analisis bisnis untuk strategi promosi atau pricing berikutnya.

9. Simpan Hasil Pembersihan
"""

# Simpan dataset bersih
df.to_csv('/content/drive/MyDrive/dataset_cleaned.csv', index=False)